import type { Metadata } from "next";
import Navbar from "./Components/Navbar";
import "./globals.css";
import localFont from "next/font/local"
import Footer from "./Components/Footer";

const myFont = localFont({
  src: [
    {
      path: './Founders_Grotesk_Font_Family_(Fontmirror)/Test Founders Grotesk 400.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './Founders_Grotesk_Font_Family_(Fontmirror)/Test Founders Grotesk Italic 400.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './Founders_Grotesk_Font_Family_(Fontmirror)/Test Founders Grotesk Medium 500.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './Founders_Grotesk_Font_Family_(Fontmirror)/Test Founders Grotesk SmB 600.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './Founders_Grotesk_Font_Family_(Fontmirror)/Test Founders Grotesk Light 300.otf',
      weight: '300',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Vacancies in Ghana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} text-lg  w-full min-h-[100vh] mx-auto overflow-x-hidden max-w-[1500px]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>  
  ); 
}
